### ISSUE TITLE
Add as npmjs maintainer?

### ISSUE THREAD

**Issue by JayV30** [lmihaidaniel/simple-scorm-packager#5]
Hi @lmihaidaniel -

Thanks for adding me as a collaborator on this project. My assumption is that you'd like minimal involvement moving forward? (as long as there are no major issues of course) Please correct me if my assumption is wrong.

Any chance you could add me as an additional npmjs maintainer so I can push updates to npm? (username: jayv30)

If not I understand. Thanks again for the awesome packager!

**Comment by lmihaidaniel** [comment]
done
